# Generated by Django 4.2 on 2024-07-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='gender',
            field=models.CharField(choices=[('S', 'Suspenso'), ('C', 'Comedia'), ('A', 'Acción'), ('T', 'Terror')], max_length=30),
        ),
    ]
