# Generated by Django 4.2 on 2024-07-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='gender',
            field=models.CharField(choices=[('T', 'Terror'), ('A', 'Acción'), ('S', 'Suspenso'), ('C', 'Comedia')], max_length=30),
        ),
    ]
