# Generated by Django 4.2 on 2024-07-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='movie',
            name='gender',
            field=models.CharField(choices=[('A', 'Acción'), ('S', 'Suspenso'), ('C', 'Comedia'), ('T', 'Terror')], max_length=30),
        ),
    ]
