# Generated by Django 4.2 on 2024-07-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_title_movie_name_alter_movie_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='gender',
            field=models.CharField(choices=[('T', 'Terror'), ('C', 'Comedia'), ('S', 'Suspenso'), ('A', 'Acción')], max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='publication',
            field=models.CharField(max_length=30),
        ),
    ]
